name: Release Build Manual

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      build_android:
        description: Build Android APK artifacts
        required: true
        type: boolean
        default: true
      build_ios:
        description: Build iOS IPA artifacts
        required: true
        type: boolean
        default: false
      build_linux:
        description: Build Linux zip artifacts
        required: true
        type: boolean
        default: true
      build_macos:
        description: Build MacOS app artifacts
        required: true
        type: boolean
        default: false
      build_windows:
        description: Build Windows zip artifacts
        required: true
        type: boolean
        default: false
      dry_run:
        description: Dry run = true 只构建，不上传到Release；false 构建并发布预发行版
        required: true
        type: boolean
        default: true

env:
  CI_FLUTTER_VERSION: "3.24.5"

jobs:
  build-linux:
    name: Build Linux
    if: ${{ github.event_name == 'pull_request' || inputs.build_linux }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get short commit hash
        run: echo "COMMIT_SHORT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Install system dependencies
        run: |
          sudo apt-get install curl unzip xz-utils zip libglu1-mesa clang cmake ninja-build pkg-config libayatana-appindicator3-dev libgtk-3-dev liblzma-dev libstdc++-12-dev -y

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{env.CI_FLUTTER_VERSION}}
          cache: true

      - run: flutter --version
      - run: flutter pub get

      - name: Build Linux release
        run: flutter build linux --release

      - name: Package Linux zip
        run: |
          cd build/linux/x64/release/bundle
          zip -r masiro-${{ env.COMMIT_SHORT_HASH }}-linux.zip .
        working-directory: ${{ github.workspace }}

      - name: Upload Linux artifact to workflow
        if: ${{ inputs.build_linux && !inputs.dry_run }}
        uses: actions/upload-artifact@v4
        with:
          name: masiro-linux-build
          path: build/linux/x64/release/bundle/masiro-${{ env.COMMIT_SHORT_HASH }}-linux.zip

      - name: Upload to GitHub PreRelease
        if: ${{ github.event_name == 'workflow_dispatch' && !inputs.dry_run && inputs.build_linux }}
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: build/linux/x64/release/bundle/masiro-${{ env.COMMIT_SHORT_HASH }}-linux.zip
          tag: ${{ env.COMMIT_SHORT_HASH }}
          prerelease: true

  build-android:
    name: Build Android
    if: ${{ github.event_name == 'pull_request' || inputs.build_android }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get short commit hash
        run: echo "COMMIT_SHORT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - run: echo "RELEASE_DIR=release" >> $GITHUB_ENV

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{env.CI_FLUTTER_VERSION}}
          cache: true

      - run: flutter --version
      - run: flutter pub get

      - name: Build split ABI APK
        run: flutter build apk --split-per-abi --no-tree-shake-icons

      - name: Rename APK
        run: |
          mkdir -p ${{ env.RELEASE_DIR }}
          cp build/app/outputs/flutter-apk/app-arm64-v8a-release.apk ${{ env.RELEASE_DIR }}
          cp build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk ${{ env.RELEASE_DIR }}
          cd ${{ env.RELEASE_DIR }}
          mv app-arm64-v8a-release.apk masiro-${{ env.COMMIT_SHORT_HASH }}-arm64-v8a-release.apk
          mv app-armeabi-v7a-release.apk masiro-${{ env.COMMIT_SHORT_HASH }}-armeabi-v7a-release.apk

      - name: Sign app APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: ${{ env.RELEASE_DIR }}
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Upload signed APK to workflow artifact
        if: ${{ inputs.build_android && !inputs.dry_run }}
        uses: actions/upload-artifact@v4
        with:
          name: masiro-android-apk
          path: ${{ env.RELEASE_DIR }}/masiro-${{ env.COMMIT_SHORT_HASH }}-*-release-signed.apk

      - name: Upload APK to GitHub PreRelease
        if: ${{ github.event_name == 'workflow_dispatch' && !inputs.dry_run && inputs.build_android }}
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "${{ env.RELEASE_DIR }}/masiro-${{ env.COMMIT_SHORT_HASH }}-*-release-signed.apk"
          tag: ${{ env.COMMIT_SHORT_HASH }}
          prerelease: true

  build-windows:
    name: Build Windows
    if: ${{ github.event_name == 'pull_request' || inputs.build_windows }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get short commit hash
        run: echo "COMMIT_SHORT_HASH=$(git rev-parse --short HEAD)" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{env.CI_FLUTTER_VERSION}}

      - run: flutter --version
      - run: flutter pub get

      - name: Build Windows release
        run: flutter build windows --release

      - name: Package Windows zip
        shell: pwsh
        run: |
          $zipName = "masiro-$env:COMMIT_SHORT_HASH-windows.zip"
          cd build/windows/x64/runner/Release
          Compress-Archive -Path * -DestinationPath $zipName
          Move-Item $zipName $env:GITHUB_WORKSPACE

      - name: Upload Windows artifact to workflow
        if: ${{ inputs.build_windows && !inputs.dry_run }}
        uses: actions/upload-artifact@v4
        with:
          name: masiro-windows-build
          path: masiro-${{ env.COMMIT_SHORT_HASH }}-windows.zip

      - name: Upload to GitHub PreRelease
        if: ${{ github.event_name == 'workflow_dispatch' && !inputs.dry_run && inputs.build_windows }}
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: masiro-${{ env.COMMIT_SHORT_HASH }}-windows.zip
          tag: ${{ env.COMMIT_SHORT_HASH }}
          prerelease: true

  build-macos-and-ios:
    name: Build MacOS & iOS
    if: ${{ github.event_name == 'pull_request' || inputs.build_macos || inputs.build_ios }}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get short commit hash
        run: echo "COMMIT_SHORT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{env.CI_FLUTTER_VERSION}}
          cache: true

      - run: flutter --version
      - run: flutter pub get

      - name: Build MacOS
        if: ${{ github.event_name == 'pull_request' || inputs.build_macos }}
        run: flutter build macos --release

      - name: Zip MacOS app
        if: ${{ github.event_name == 'pull_request' || inputs.build_macos }}
        run: |
          cd build/macos/Build/Products/Release
          zip -r masiro-${{ env.COMMIT_SHORT_HASH }}-macos.zip "masiro icon.app"

      - name: Upload MacOS artifact
        if: ${{ inputs.build_macos && !inputs.dry_run }}
        uses: actions/upload-artifact@v4
        with:
          name: masiro-macos-build
          path: build/macos/Build/Products/Release/masiro-${{ env.COMMIT_SHORT_HASH }}-macos.zip

      - name: Upload MacOS to PreRelease
        if: ${{ github.event_name == 'workflow_dispatch' && !inputs.dry_run && inputs.build_macos }}
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: build/macos/Build/Products/Release/masiro-${{ env.COMMIT_SHORT_HASH }}-macos.zip
          tag: ${{ env.COMMIT_SHORT_HASH }}
          prerelease: true

      - name: Build iOS ipa
        if: ${{ github.event_name == 'pull_request' || inputs.build_ios }}
        run: flutter build ios --release --no-codesign

      - name: Packing IPA
        if: ${{ github.event_name == 'pull_request' || inputs.build_ios }}
        run: |
          mkdir Payload
          mv build/ios/iphoneos/Runner.app Payload
          zip -r9 masiro-${{ env.COMMIT_SHORT_HASH }}.ipa Payload

      - name: Upload iOS artifact
        if: ${{ inputs.build_ios && !inputs.dry_run }}
        uses: actions/upload-artifact@v4
        with:
          name: masiro-ios-build
          path: masiro-${{ env.COMMIT_SHORT_HASH }}.ipa

      - name: Upload iOS to PreRelease
        if: ${{ github.event_name == 'workflow_dispatch' && !inputs.dry_run && inputs.build_ios }}
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: masiro-${{ env.COMMIT_SHORT_HASH }}.ipa
          tag: ${{ env.COMMIT_SHORT_HASH }}
          prerelease: true
